name: PHP CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create SQLite database file
        run: mkdir -p database && touch database/database.sqlite

      - name: Create .env for testing
        run: |
          rm -f .env
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=$(pwd)/database/database.sqlite" >> .env
          echo "CACHE_DRIVER=array" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
          echo "SESSION_DRIVER=array" >> .env
          php artisan key:generate --show | xargs -I {} echo "APP_KEY={}" >> .env

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test

      - name: Upload code coverage to SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Remove .env and test DB after tests
        run: |
          rm -f .env
          rm -f database/database.sqlite
